### ISSUE TITLE
Use of uninitialized value in substr at get_taxa_from_diamond.pl line 96 (#1)

### ISSUE THREAD

**Issue by desmondramirez** [Lafond-LapalmeJ/MCSC_Decontamination#26]
Hi,

I'm trying to run MCSC decontamination, but keep getting errors when the script tries to use the get_taxa_from_diamond.pl script. As of diamond 0.9.19, the diamond database format is different from previous versions (e.g. 0.8.22, which seems to be what was used to create the test diamond database). Is it possible that the database update has broken the perl script?

The errors are : "Use of uninitialized value in substr" and "Use of uninitialized value in concatenation (.) or string" at line 96 of the get_taxa_from_diamond.pl script.

I suppose I can install an older version of diamond to make the script work, but any other suggestions are greatly appreciated.

Thanks,
Des

**Comment by charlesfoster** [comment]
Hi,

I encountered the same issue as @desmondramirez . I've tried using both Diamond 0.9.10 and 0.8.28.90 (the two versions on my cluster). Error:

"Use of uninitialized value in substr at
        /my_path/scripts/get_taxa_from_diamond.pl line 96 (#1)
    (W uninitialized) An undefined value was used as if it were already
    defined.  It was interpreted as a "" or a 0, but maybe it was a mistake.
    To suppress this warning assign a defined value to your variables.

    To help you figure out what was undefined, perl will try to tell you
    the name of the variable (if any) that was undefined.  In some cases
    it cannot do this, so it also tells you what operation you used the
    undefined value in.  Note, however, that perl optimizes your program
    and the operation displayed in the warning may not necessarily appear
    literally in your program.  For example, "that $foo" is usually
    optimized into "that " . $foo, and the warning will refer to the
    concatenation (.) operator, even though there is no . in
    your program.

Use of uninitialized value in concatenation (.) or string at
        /my_path/scripts/get_taxa_from_diamond.pl line 96 (#1)"

Has there been a solution discovered yet?

Cheers,
Charles

**Comment by Lafond-LapalmeJ** [comment]
Hi Charles,

The pipeline should work even with this perl warning. But anyway I have fix
it and push to github. I have test it using diamond v0.9.22 and v0.9.10 and
everything looks fine. If you have more problems please send me you
complete output.

Cheers,
Joël


Le dim. 12 août 2018 à 22:32, charlesfoster <notifications@github.com> a
écrit :
