### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by AlsoATraveler** [Lafond-LapalmeJ/MCSC_Decontamination#27]
When I run sh MCSC_decontamination.sh xxx.ini，get the following error
Use of uninitialized value $taxa1 in concatenation (.) or string at /mnt/MD3400/data003/qiuyinbin/ref/MCSC/MCSC_Decontamination/scripts/cluster_eval.pl line 117
The phylum Chordata is not present in taxo_uniq.txt file. Aborting
how can I fix？

**Comment by xing-he529** [comment]
hello, I got the same error as yours, did you fix it?
