### ISSUE TITLE
error running the MCSC algorithm and no output *cluster_*.fasta

### ISSUE THREAD

**Issue by Liyong-Zhang** [Lafond-LapalmeJ/MCSC_Decontamination#31]
Hello there,

I am trying to use MCSC to remove the potential contamination of my de novo assembled transcripts. 

I followed the exact pipeline as yours, and everything running fine till 
    Running the MCSC algorithm...
  ./MCSC_decontamination.sh: line 150: /Users/Liyong/bioinfo/MCSC_De/MCSC_Decontamination/scripts/mcsc_fix: cannot execute 
   binary file
   sed: 1: "/Users/Liyong/bioinfo/M ...": invalid command code L

Then it continues with Computing the White-Ratio (WR) index and evaluating the clusters...

and Printing MCSC output results...

However, not output cluster_.fasta files, see below the error:
  mv: rename /Users/Liyong/bioinfo/MCSC_De/output_or//*cluster_*.fasta to 
  /Users/Liyong/bioinfo/MCSC_De/output_or//clusters/*cluster_*.fasta: No such file or directory
  Done

Could you help me take a look when you get a chance?   Thank you!

**Comment by Liyong-Zhang** [comment]
To follow up, I am running this pipeline in macOS, which might be the problem.  After I checked the file of mcsc_fix, it shows
  mcsc_fix: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, 
  for GNU/Linux 2.6.24.

I have searched how to run Linux binary on macOS, couldn't fix it on my own. 

Do you have a macOS version of this pipeline?    Thank you!

**Comment by Lafond-LapalmeJ** [comment]
I don't think it works on a macOS. Unless you have a Linux VM or a Docker container on your mac. It's not possible for me to produce a macOS version for the mcsc_fix executable. If you have access to a Linux computer you can run it once and then transfer the output folder to your mac computer. From there, you can rerun the same dataset with different settings or target taxon with the command `sh MCSC_Decontamination file.ini --recalculate` , With `--recalculate` the clustering step (mcsc_fix) will be skipped.

Thank you

**Comment by Liyong-Zhang** [comment]
Thank you for the response.  That's good to know. For sure, I will try it on Linux first.

Regards,
